version: '3'
services:
  database:
    container_name: weather-forecast-database
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_root_password
      - POSTGRES_DB=postgres
    ports:
      - 5442:5432
    volumes:
      - ./infrastructure/database/data:/var/lib/postgresql/data/

  pgadmin:
    container_name: weather-forecast-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  test-database:
    container_name: weather-forecast-test-database
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_root_password
      - POSTGRES_DB=test
    ports:
      - 5443:5432
